python tf_gp_dcgan.py 0 tf_gp_dcgan_0_5epochs
python tf_gp_dcgan.py 1 tf_gp_dcgan_1_5epochs
python tf_gp_dcgan.py 2 tf_gp_dcgan_2_5epochs
python tf_gp_dcgan.py 3 tf_gp_dcgan_3_5epochs
python tf_gp_dcgan.py 4 tf_gp_dcgan_4_5epochs
python tf_gp_dcgan.py 5 tf_gp_dcgan_5_5epochs
python tf_gp_dcgan.py 6 tf_gp_dcgan_6_5epochs
python tf_gp_dcgan.py 7 tf_gp_dcgan_7_5epochs
python tf_gp_dcgan.py 8 tf_gp_dcgan_8_5epochs
python tf_gp_dcgan.py 9 tf_gp_dcgan_9_5epochs
python dcgan.py 0 dcgan_0_5epochs
python dcgan.py 1 dcgan_1_5epochs
python dcgan.py 2 dcgan_2_5epochs
python dcgan.py 3 dcgan_3_5epochs
python dcgan.py 4 dcgan_4_5epochs
python dcgan.py 5 dcgan_5_5epochs
python dcgan.py 6 dcgan_6_5epochs
python dcgan.py 7 dcgan_7_5epochs
python dcgan.py 8 dcgan_8_5epochs
python dcgan.py 9 dcgan_9_5epochs
